# Generated by Django 4.2 on 2023-04-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pribadi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='foto',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
