# Generated by Django 4.2 on 2023-04-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pribadi', '0002_profil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='foto',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
