# Generated by Django 4.2 on 2023-04-08 06:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pribadi', '0003_alter_profil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_foto', models.CharField(blank=True, max_length=250, null=True)),
                ('foto', models.ImageField(blank=True, max_length=250, null=True, upload_to='')),
                ('judul_album', models.CharField(blank=True, max_length=250, null=True)),
                ('tanggal', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Album Foto',
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=250, null=True)),
                ('isi_artikel', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('foto_artikel', models.ImageField(blank=True, max_length=250, null=True, upload_to='')),
                ('penulis', models.CharField(blank=True, max_length=250, null=True)),
                ('tanggal', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Artikel',
            },
        ),
        migrations.CreateModel(
            name='Khutbah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulis', models.CharField(blank=True, max_length=250, null=True)),
                ('judul', models.CharField(blank=True, max_length=250, null=True)),
                ('isi_khutbah', ckeditor.fields.RichTextField()),
                ('foto_khutbah', models.ImageField(blank=True, max_length=250, null=True, upload_to='')),
                ('tanggal', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Khutbah',
            },
        ),
        migrations.AlterField(
            model_name='profil',
            name='tentang_diri',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
