# Generated by Django 4.2 on 2023-04-08 07:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pribadi', '0004_album_artikel_khutbah_alter_profil_tentang_diri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khutbah',
            name='isi_khutbah',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
