# Generated by Django 4.2 on 2023-04-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pribadi', '0005_alter_khutbah_isi_khutbah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='foto',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='foto_artikel',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='khutbah',
            name='foto_khutbah',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='foto',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='foto/'),
        ),
    ]
