# Generated by Django 4.2 on 2023-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pribadi', '0006_alter_album_foto_alter_artikel_foto_artikel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='foto',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='foto_artikel',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='khutbah',
            name='foto_khutbah',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profil',
            name='foto',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=''),
        ),
    ]
